### ISSUE TITLE
What is the License of the repository?

### ISSUE THREAD

**Issue by gfenoy** [MapServer/ms-ogc-workshop#2]
If there is a list of contributors at the end of the powerpoint document, I was wondering what is the current license for the material shared in this repository.

I am currently working on a Tale (https://wholetale.org) using the current ms-ogc-workshop material and MapServer embedded within the Docker environment started from wholetale.org. Also, I was willing to use a DOI for the current material. Nevertheless, as there is no license provided, I am unable to proceed.

Also, I was wondering if you have any plan to release the current material. In such a case, would you mind creating a DOI on [zenodo](https://zenodo.org/) for instance when publishing your release?

**Comment by sdlime** [comment]
@tomkralidis, what do you think? You're listed as the contact for this content... --Steve

**Comment by tomkralidis** [comment]
I'm good with putting forth a CC BY 4.0 for the repo if that works for folks (see #4).

**Comment by sdlime** [comment]
Fine by me... @gfenoy, does that work for you?

**Comment by jmckenna** [comment]
@tomkralidis looks good here (license draft) +1

**Comment by jmckenna** [comment]
By the way, this workshop has been included in the MS4W installation for so long (6k downloads/month), it's still a great resource!!!

**Comment by gfenoy** [comment]
That is just perfect, thanks!
